library/controllers/autorController.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from models.autor import*
from dao.autorDao import*
from repository.autorRepository import AutorRepository

autoresController = Blueprint('autores', __name__)
repository = AutorRepository()

# Rota para buscar autor por ID
@autoresController.route('/get-autores', methods=['GET', 'POST'])
def autor_porid():
    if request.method == 'POST':
        id = request.form.get('id')
        autor = repository.get_autor(id)
        if autor:
            flash(f'Autor encontrado: {autor.nome}')
        else:
            flash('Autor não encontrado. Tente novamente!')
    return render_template('autores.html')

# Rota para listar todos os autores
@autoresController.route('/get-all-autores', methods=['GET', 'POST'])
def get_all_autores():
    all_autores = None
    if request.method == 'POST':
        all_autores = repository.get_all_autor()
    return render_template('autores.html', all_autores=all_autores)

# Rota para criar um novo autor
@autoresController.route('/criar-autor', methods=['GET', 'POST'])
def criar_autor():
    autor = None
    if request.method == 'POST':
        nome = request.form.get('nome')
        data_nasci = request.form.get('data_nasci')
        nacionalidade = request.form.get('nacionalidade')
        autor = repository.criar_autor(nome, data_nasci, nacionalidade)
    return render_template('autores.html', autor=autor)

# Rota para editar autor
@autoresController.route('/editar_autor/<int:id>', methods=['POST'])
def editar_autor(id):
    nome = request.form.get('nome')
    data_nasci = request.form.get('data_nasci')
    nacionalidade = request.form.get('nacionalidade')
    repository.atualizar_autor(id, nome, data_nasci, nacionalidade)
    flash('Autor atualizado com sucesso!')
    return redirect(url_for('autores.get_all_autores'))

# Rota para excluir autor
@autoresController.route('/excluir_autor/<int:id>', methods=['POST'])
def excluir_autor(id):
    repository.deletar_autor(id)
    flash('Autor excluído com sucesso!')
    return redirect(url_for('autores.get_all_autores'))

library/controllers/generosController.py
from flask import *
from models.generos import *
from dao.generosDao import*
from repository.generosRepository import*

generosController = Blueprint('generos', __name__)
repository = GenerosRepository()

@generosController.route('/get-generos', methods=['GET', 'POST'])
def genero_porid():
    if request.method == 'POST':
        id = request.form.get('id')
        genero = repository.get_generos(id)  # procura o genero pelo id
        if genero:
            flash(f'gênero encontrado: id: {genero.id}, gênero: {genero.tipo}')
        else:
            flash('desculpe, não encontramos nenhum gênero com esse id... mas você pode cadastrar um novo abaixo, se quiser!')
    return render_template('categorias.html')

@generosController.route('/get-all-generos', methods=['GET', 'POST'])
def get_all_generos():
    all_generos = None
    if request.method == 'POST':
        all_generos = repository.get_all_generos()
    return render_template('categorias.html', all_generos=all_generos)

@generosController.route('/criar-genero', methods=['GET', 'POST'])
def criar_genero():
    gener = None
    if request.method == 'POST':
        tipo = request.form.get('tipo')
        gener = repository.criar_generos(tipo)
    return render_template('categorias.html', gener=gener)

@generosController.route('/editar_categoria/<int:id>', methods=['POST'])
def editar_categoria(id):
    gener = request.form.get('gener')
    repository.atualizar_generos(id, gener)
    flash('gênero literário atualizado com sucesso!')
    return redirect(url_for('generos.get_all_generos'))

@generosController.route('/excluir_categoria/<int:id>', methods=['POST'])
def excluir_categoria(id):
    repository.deletar_generos(id)
    flash('gênero literário excluído com sucesso!')
    return redirect(url_for('generos.get_all_generos'))

library/controllers/livrosController.py
from flask import *
from repository.livrosRepository import*

livrinhosController = Blueprint('livrinhos', __name__)
repository = LivrosRepository()


@livrinhosController.route('/books')
def livros():
    return render_template("livrinhos.html")


@livrinhosController.route('/get-all-livros', methods=['GET', 'POST'])
def get_all_livros():
    all_livros = None
    if request.method == 'POST':
        all_livros = repository.get_all_livros()
    return render_template('livrinhos.html', all_livros=all_livros)


@livrinhosController.route('/criarlivro', methods=['GET', 'POST'])
def criar_livro():
    if request.method == 'POST':
        titulo = request.form.get('titulo')
        isbn = request.form.get('isbn')
        num_pag = request.form.get('num_pag')
        autor_id = request.form.get('autor_id')
        genero_id = request.form.get('genero_id')
        livro = repository.criar_livros(titulo, isbn, num_pag, autor_id, genero_id)
        flash('Livro criado com sucesso!')
        return redirect(url_for('livrinhos.get_all_livros'))
    
    return render_template('criar.html')


@livrinhosController.route('/editar_livro/<int:id>', methods=['GET', 'POST'])
def editar_livro(id):
    livro = repository.get_livro(id)
    
    if request.method == 'POST':
        titulo = request.form.get('titulo')
        isbn = request.form.get('isbn')
        num_pag = request.form.get('num_pag')
        autor_id = request.form.get('autor_id')
        genero_id = request.form.get('genero_id')
        repository.atualizar_Livros(id, titulo, isbn, num_pag, autor_id, genero_id)
        flash('livro atualizado')
        return redirect(url_for('livrinhos.get_all_livros'))
    
    return render_template('editar.html', livro=livro)


@livrinhosController.route('/excluir_livro/<int:id>', methods=['POST'])
def excluir_livro(id):
    repository.deletar_Livros(id)
    flash('livro excluído')
    return redirect(url_for('livrinhos.get_all_livros'))

library/templates/autores.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Autores</title>
</head>
<style>
    a {
        background-color: rgb(182, 182, 219);
        color: rgb(4, 52, 93);
        padding: 20px;
        margin: 30px;
        display: flex;
        justify-content: center;
    }
    h1 {
        color: darkblue;
        font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;
        text-align: center;
    }
    h2 {
        color: rgb(82, 82, 158);
        text-align: center;
    }
    h3{
        color: rgb(82, 82, 158);
        text-align: center;
    }
    input {
        background-color: rgba(210, 210, 232, 0.842);
        color: darkblue;
    }
    .flashes {
        list-style-type: none;
        padding: 0;
        text-align: center;
    }
</style>
<body>
    <h1>kams' bookstore!</h1>

    <!-- Buscar autor por ID -->
    <form action="/get-autores" method="POST">
        <label for="id">Deseja verificar qual autor corresponde a um ID? Digite-o abaixo:</label>
        <input type="number" name="id" required>
        <button type="submit">Verificar</button>
    </form>

    {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
            <ul class="flashes">
            {% for category, message in messages %}
                <li class="{{ category }}">{{ message }}</li>
            {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}

    <!-- Listar todos os autores -->
    <form action="/get-all-autores" method="POST">
        <label for="all">Deseja verificar todos os autores e seus IDs correspondentes? Clique no botão abaixo:</label>
        <input type="submit" name="all_autores">
    </form>

    {% if all_autores %}
    <div class="result">
        <h2>Aqui está uma lista com todos os autores!</h2>
        <ul>
            {% for autor in all_autores %}
            <li>
                id: {{ autor.id }} - Nome: {{ autor.nome }} - Nacionalidade: {{ autor.nacionalidade }} - Data de Nascimento: {{ autor.data_nasci }}
                <form action="{{ url_for('autores.editar_autor', id=autor.id) }}" method="post" style="display:inline;">
                    <input type="text" name="nome" placeholder="Novo nome" required>
                    <input type="date" name="data_nasci" required>
                    <input type="text" name="nacionalidade" placeholder="Nova nacionalidade" required>
                    <button type="submit">Editar</button>
                </form>
                <form action="{{ url_for('autores.excluir_autor', id=autor.id) }}" method="post" style="display:inline;">
                    <button type="submit">Excluir</button>
                </form>
            </li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

    <!-- Criar novo autor -->
    <form action="/criar-autor" method="POST">
        <label for="nome">Nome do autor:</label>
        <input type="text" name="nome" required>
        <label for="data_nasci">Data de nascimento:</label>
        <input type="date" name="data_nasci" required>
        <label for="nacionalidade">Nacionalidade:</label>
        <input type="text" name="nacionalidade" required>
        <button type="submit">Criar autor</button>
    </form>

    <h3>qual caminho você quer fazer agora?</h3>
    <a onclick="window.location.href='/'"> voltar a pagina inicial</a>
    <a onclick="window.location.href='/books'">livros</a>
    <a onclick="window.location.href='/authors'">autores</a>
    <a onclick="window.location.href='/categorias'">categorias/generos literários</a>
</body>
</html>

library/templates/categorias.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>categorias!</title>
</head>
<style>
a{
    background-color: rgb(182, 182, 219);
    color:rgb(4, 52, 93);
    padding: 20px;
    margin:30px;
    display: flex;
    justify-content: center;
}
h1{
    color: darkblue;
    font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;
    text-align: center;
}
h2{
    color:rgb(82, 82, 158);
    text-align: center;
}
input{
    background-color: rgba(210, 210, 232, 0.842);
    color: darkblue;
}
.flashes {
    list-style-type: none;
    padding: 0;
    text-align: center;
}
</style>
<body>
    <h1>kams' bookstore!</h1>
    <form action="/get-generos" method="POST">
        <label for="id">deseja verificar qual categoria corresponde a um ID? digite-o abaixo!</label>
        <input type="number" name="id" required>
        <button type="submit">verificar</button>
    </form>

    {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
            <ul class="flashes">
            {% for category, message in messages %}
                <li class="{{ category }}">{{ message }}</li>
            {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}

    <form action="/get-all-generos" method="POST">
        <label for="all">deseja verificar todas as categorias e seus IDs correspondentes? clique no botão abaixo:</label>
        <input type="submit" name="all_generos">
    </form>

    {% if all_generos %}
    <div class="result">
        <h2>here's a list with all the categories we have!</h2>
        <ul>
            {% for genero in all_generos %}
            <li>
                id: {{ genero.id }} - gênero literário: {{ genero.tipo }}
                <form action="{{ url_for('generos.editar_categoria', id=genero.id) }}" method="post" style="display:inline;">
                    <input type="text" name="gener" placeholder="digite aqui o novo gênero" required>
                    <button type="submit">editar</button>
                </form>
                <form action="{{ url_for('generos.excluir_categoria', id=genero.id) }}" method="post" style="display:inline;">
                    <button type="submit">deletar</button>
                </form>
            </li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

    <form action="/criar-genero" method="POST">
        <label for="tipo">deseja criar umo novo gênero literário? digite o tipo abaixo:</label>
        <input type="text" name="tipo" required>
        <button type="submit">criar gênero literário!</button>
    </form>

    {% if gener %}
        <div class="result">
            <h2>novo gênero criado:</h2>
            <p>ID: {{ gener.id }}</p>
            <p>Categoria: {{ gener.tipo }}</p>
        </div>
    {% endif %}




    <h3>qual caminho você quer fazer agora?</h3>
    <a onclick="window.location.href='/'"> voltar a pagina inicial</a>
    <a onclick="window.location.href='/books'">livros</a>
    <a onclick="window.location.href='/authors'">autores</a>
    <a onclick="window.location.href='/categorias'">categorias/generos literários</a>
</body>
</html>

library/templates/criar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>criar!</title>
</head>
<style>
    a {
        background-color: rgb(182, 182, 219);
        color: rgb(4, 52, 93);
        padding: 20px;
        margin: 30px;
        display: flex;
        justify-content: center;
    }
    h1 {
        color: darkblue;
        font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;
        text-align: center;
    }
    h2 {
        color: rgb(82, 82, 158);
        text-align: center;
    }
    input {
        background-color: rgba(210, 210, 232, 0.842);
        color: darkblue;
    }
    .flashes {
        list-style-type: none;
        padding: 0;
        text-align: center;
    }
</style>
<body>
    <h1>preencha  form abaixo e crie um novo livro!</h1>
    <form action="/criarlivro" method="POST">
        <label for="titulo">título:</label>
        <input type="text" name="titulo" required><br>
        <label for="isbn">ISBN:</label>
        <input type="text" name="isbn" required><br>
        <label for="num_pag">numero de paginas:</label>
        <input type="number" name="num_pag" required><br>
        <label for="autor_id">id do autor:</label>
        <input type="number" name="autor_id" required><br>
        <label for="genero_id">id do genero:</label>
        <input type="number" name="genero_id" required><br>
        <button type="submit">criar livro</button>
    </form>
    
    <h3>qual caminho você quer fazer agora?</h3>
    <a onclick="window.location.href='/'"> voltar a pagina inicial</a>
    <a onclick="window.location.href='/books'">livros</a>
    <a onclick="window.location.href='/authors'">autores</a>
    <a onclick="window.location.href='/categorias'">categorias/generos literários</a>
</body>
</html>

library/templates/editar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>editar!</title>
</head>
<body>
    <style>
        a {
            background-color: rgb(182, 182, 219);
            color: rgb(4, 52, 93);
            padding: 20px;
            margin: 30px;
            display: flex;
            justify-content: center;
        }
        h1 {
            color: darkblue;
            font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;
            text-align: center;
        }
        h2 {
            color: rgb(82, 82, 158);
            text-align: center;
        }
        input {
            background-color: rgba(210, 210, 232, 0.842);
            color: darkblue;
        }
        .flashes {
            list-style-type: none;
            padding: 0;
            text-align: center;
        }
    </style>
    <h1>preencha o form abaixo e edite o livro!</h1>
    <form action="/editar_livro/{{ livro.id }}" method="POST">
        <label for="titulo">título:</label>
        <input type="text" name="titulo" value="{{ livro.titulo }}" required><br>
        <label for="isbn">ISBN:</label>
        <input type="text" name="isbn" value="{{ livro.isbn }}" required><br>
        <label for="num_pag">número de páginas:</label>
        <input type="number" name="num_pag" value="{{ livro.num_pag }}" required><br>
        <label for="autor_id">id do autor:</label>
        <input type="number" name="autor_id" value="{{ livro.autor_id }}" required><br>
        <label for="genero_id">id do genero:</label>
        <input type="number" name="genero_id" value="{{ livro.genero_id }}" required><br>
        <button type="submit">atualizar livro</button>
    </form>
    
    <h3>qual caminho você quer fazer agora?</h3>
    <a onclick="window.location.href='/'"> voltar a pagina inicial</a>
    <a onclick="window.location.href='/books'">livros</a>
    <a onclick="window.location.href='/authors'">autores</a>
    <a onclick="window.location.href='/categorias'">categorias/generos literários</a>
</body>
</html>

library/templates/index.html
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>kams' bookstore</title>
    </head>
    <style>
    a{
        background-color: rgb(182, 182, 219);
        color:rgb(4, 52, 93);
        padding: 20px;
        margin:30px;
        display: flex;
        justify-content: center;
    }
    h1{
        color: darkblue;
        font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;
        text-align: center;
    }
    h3{
        color:rgb(82, 82, 158);
        text-align: center;
    }
    </style>
    <body>
        <h1>welcome to the most magic bookstore that you ever saw in your live!</h1>
        <h3>qual caminho você quer fazer agora?</h3>
        <a onclick="window.location.href='/books'">livros</a>
        <a onclick="window.location.href='/autores'">autores</a>
        <a onclick="window.location.href='/categorias'">categorias/generos literários</a>
    </body>
    </html>

library/templates/livrinhos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>livros!</title>
    <style>
        a {
            background-color: rgb(182, 182, 219);
            color: rgb(4, 52, 93);
            padding: 20px;
            margin: 30px;
            display: flex;
            justify-content: center;
        }
        h1 {
            color: darkblue;
            font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;
            text-align: center;
        }
        h2 {
            color: rgb(82, 82, 158);
            text-align: center;
        }
        input {
            background-color: rgba(210, 210, 232, 0.842);
            color: darkblue;
        }
        .flashes {
            list-style-type: none;
            padding: 0;
            text-align: center;
        }
    </style>
</head>
<body>
    <h1>kams' bookstore!</h1>

    <form action="/get-all-livros" method="POST">
        <button type="submit">ver todos os livros</button>
    </form>

    {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
            <ul class="flashes">
            {% for category, message in messages %}
                <li class="{{ category }}">{{ message }}</li>
            {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}
    
    {% if all_livros %}
    <div class="result">
        <h2>abaixo está a lista com todo os livros e suas caracteristicas</h2>
        <ul>
            {% for livro in all_livros %}
            <li>
                id: {{ livro.id }} - título: {{ livro.titulo }} - ISBN: {{ livro.isbn }} - data de publicação: {{ livro.data_publi }} - número de páginas: {{ livro.num_pag }} - autor(es): {{ livro.autor_id }} - gênero literário: {{ livro.genero_id }}
                <form action="{{ url_for('livrinhos.editar_livro', id=livro.id) }}" method="get" style="display:inline;">
                    <button type="submit">editar</button>
                </form>
                <form action="{{ url_for('livrinhos.excluir_livro', id=livro.id) }}" method="post" style="display:inline;">
                    <button type="submit">deletar</button>
                </form>
            </li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}

    <div style="text-align:center;">
        <a onclick="window.location.href='/criarlivro'">quer criar um livro? clique aqui!</a>
    </div>

    <h3>qual caminho você quer fazer agora?</h3>
    <a onclick="window.location.href='/'"> voltar a pagina inicial</a>
    <a onclick="window.location.href='/books'">livros</a>
    <a onclick="window.location.href='/authors'">autores</a>
    <a onclick="window.location.href='/categorias'">categorias/generos literários</a>
</body>
</html>